version: ~> 1.0
branches:
  only:
    - master
    - prerelease
# Caching of node_modules disabled, due to an increase in delayed breakages
cache:
  npm: false
  yarn: false
  directories: null
dist: trusty
language: node_js
node_js:
  - 14
os: linux

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint:fix
  - npm run test:coverage

after_script:
  # Format coverage results to be where and how cc-test-reporter expects them
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.json -t lcov coverage/lcov.info
  # Upload coverage to Code Climate
  - ./cc-test-reporter upload-coverage -i coverage/codeclimate.json
